// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoDS3Z7khTjzveluCivNT9ntNuqY3qsF0',
    appId: '1:85705829712:web:2f2df7a19eda7889845055',
    messagingSenderId: '85705829712',
    projectId: 'haven-net',
    authDomain: 'haven-net.firebaseapp.com',
    storageBucket: 'haven-net.firebasestorage.app',
    measurementId: 'G-4135FMV29C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_7o-wE0Mh6dfpXDiqYwh45wvVZHXol24',
    appId: '1:85705829712:android:9ba1638c45737621845055',
    messagingSenderId: '85705829712',
    projectId: 'haven-net',
    storageBucket: 'haven-net.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjwXSp7EyQDYiqzLXg3YKVGdo9yz0Q6AQ',
    appId: '1:85705829712:ios:d0d4bf75ba54c4b0845055',
    messagingSenderId: '85705829712',
    projectId: 'haven-net',
    storageBucket: 'haven-net.firebasestorage.app',
    iosBundleId: 'com.example.havenNet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjwXSp7EyQDYiqzLXg3YKVGdo9yz0Q6AQ',
    appId: '1:85705829712:ios:d0d4bf75ba54c4b0845055',
    messagingSenderId: '85705829712',
    projectId: 'haven-net',
    storageBucket: 'haven-net.firebasestorage.app',
    iosBundleId: 'com.example.havenNet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoDS3Z7khTjzveluCivNT9ntNuqY3qsF0',
    appId: '1:85705829712:web:7bf3513a28a9fb2a845055',
    messagingSenderId: '85705829712',
    projectId: 'haven-net',
    authDomain: 'haven-net.firebaseapp.com',
    storageBucket: 'haven-net.firebasestorage.app',
    measurementId: 'G-D6YNPR5PPP',
  );
}
